module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "azul-timesazul-times-50": "var(--azul-timesazul-times-50)",
        "azul-timesazul-times-500": "var(--azul-timesazul-times-500)",
        "borda-suave": "var(--borda-suave)",
        "brand-color": "var(--brand-color)",
        "color-dark-yellow": "var(--color-dark-yellow)",
        "color-grey-3": "var(--color-grey-3)",
        "color-grey-5": "var(--color-grey-5)",
        "color-light-green": "var(--color-light-green)",
        "color-primary": "var(--color-primary)",
        "coresescala-de-cinzabranco-v1": "var(--coresescala-de-cinzabranco-v1)",
        "coresescala-de-cinzabranco-v2": "var(--coresescala-de-cinzabranco-v2)",
        "coresescala-de-cinzabranco-v3-borda":
          "var(--coresescala-de-cinzabranco-v3-borda)",
        "coresescala-de-cinzacinza": "var(--coresescala-de-cinzacinza)",
        "coresescala-de-cinzapreto-v1": "var(--coresescala-de-cinzapreto-v1)",
        coresestadossuccess: "var(--coresestadossuccess)",
        "coresmarcabrand-credliber": "var(--coresmarcabrand-credliber)",
        "escala-de-cinzabranco-v1": "var(--escala-de-cinzabranco-v1)",
        "escala-de-cinzabranco-v2": "var(--escala-de-cinzabranco-v2)",
        "escala-de-cinzabranco-v3-borda":
          "var(--escala-de-cinzabranco-v3-borda)",
        "escala-de-cinzacinza": "var(--escala-de-cinzacinza)",
        "escala-de-cinzapreto-v1": "var(--escala-de-cinzapreto-v1)",
        estadoserror: "var(--estadoserror)",
        estadosinfo: "var(--estadosinfo)",
        estadossuccess: "var(--estadossuccess)",
        estadoswarning: "var(--estadoswarning)",
        "gray-0210": "var(--gray-0210)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray02-20": "var(--gray02-20)",
        "gray02-50": "var(--gray02-50)",
        grey: "var(--grey)",
        "iconbrowser-controlslight": "var(--iconbrowser-controlslight)",
        "iconurl-controlsdisabledlight": "var(--iconurl-controlsdisabledlight)",
        "label-dark-primary": "var(--label-dark-primary)",
        "label-dark-tertiary": "var(--label-dark-tertiary)",
        "label-light-primary": "var(--label-light-primary)",
        "m-3syslightprimary": "var(--m-3syslightprimary)",
        "m3syslighton-surface-variant": "var(--m3syslighton-surface-variant)",
        "m3syslightsecondary-container": "var(--m3syslightsecondary-container)",
        "marcabrand-credliber": "var(--marcabrand-credliber)",
        "marcabrand-fgts-express": "var(--marcabrand-fgts-express)",
        "marcabrand-fgts-express-10": "var(--marcabrand-fgts-express-10)",
        "marcarosa-10": "var(--marcarosa-10)",
        "old-colorsateno": "var(--old-colorsateno)",
        "old-colorsborda-suave": "var(--old-colorsborda-suave)",
        "old-colorsbrand-color": "var(--old-colorsbrand-color)",
        "old-colorscinza": "var(--old-colorscinza)",
        "old-colorscredliber-10-brand-color":
          "var(--old-colorscredliber-10-brand-color)",
        "old-colorserro": "var(--old-colorserro)",
        "old-colorserro-background": "var(--old-colorserro-background)",
        "old-colorsinfo": "var(--old-colorsinfo)",
        "old-colorspreto-01": "var(--old-colorspreto-01)",
        "old-colorspreto-02": "var(--old-colorspreto-02)",
        "old-colorspreto-03": "var(--old-colorspreto-03)",
        preto: "var(--preto)",
        "preto-01": "var(--preto-01)",
        "primery-border": "var(--primery-border)",
        "system-bg-dark-base-primary": "var(--system-bg-dark-base-primary)",
        "systemgreen-light": "var(--systemgreen-light)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "m3-body-large": "var(--m3-body-large-font-family)",
        "m3-label-large": "var(--m3-label-large-font-family)",
        "m3-label-medium": "var(--m3-label-medium-font-family)",
        "text-normal": "var(--text-normal-font-family)",
        "text-normal-bold": "var(--text-normal-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "drop-shadoww": "var(--drop-shadoww)",
        "m3-elevation-light-1": "var(--m3-elevation-light-1)",
        "m3-elevation-light-3": "var(--m3-elevation-light-3)",
        "shadow-effect": "var(--shadow-effect)",
        shadows: "var(--shadows)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
